# simulation configuration
DEBUG = True
AVERAGE_BANDWIDTH_MODE = False
# MEDIAN_BITRATE_MODE = True
CHUNK_AWARE_MODE = False
PS_STYLE_BANDWIDTH = False
VALIDATION_MODE = False
TOTAL_CHUNKS  = 0
UTILITY_BITRATE_SELECTION = True
BANDWIDTH_UTILITY = False
BUFFERLEN_UTILITY = False
DATABRICKS_MODE = False
LOCK = 5
MAX_BUFFLEN = 120
conf = {'maxbuflen':120, 'r': 15, 'maxRPct':0.45}

 

