# simulation configuration
DEBUG = True
AVERAGE_BANDWIDTH_MODE = False
# MEDIAN_BITRATE_MODE = True
CHUNK_AWARE_MODE = False
PS_STYLE_BANDWIDTH = False
VALIDATION_MODE = False
TOTAL_CHUNKS  = 0
UTILITY_BITRATE_SELECTION = False
BANDWIDTH_UTILITY = False
BUFFERLEN_UTILITY = True
DATABRICKS_MODE = False
conf = {'maxbuflen':120, 'r': 15, 'maxRPct':0.45}

 

